services:
  accepted-purchase-processor:
    container_name: accepted-purchase-processor
    build:
      context: ./accepted-purchase-processor
      dockerfile: Dockerfile
    environment:
      - KAFKA_ADDRESS=138.2.67.89:9092
      - ACCEPTED_PURCHASE_TOPIC_NAME=accepted-purchases
      - BALANCE_ADJUSTMENT_TOPIC_NAME=balance-adjustments

  balance-adjustment-processor:
    container_name: balance-adjustment-processor
    build:
      context: ./balance-adjustment-processor
      dockerfile: Dockerfile
    environment:
      - KAFKA_ADDRESS=138.2.67.89:9092
      - BALANCE_STORE_NAME=balance-store
      - BALANCE_TOPIC_NAME=balances
      - BALANCE_ADJUSTMENT_TOPIC_NAME=balance-adjustments

  credit-card-producer:
    container_name: credit-card-producer
    build:
      context: ./credit-card-producer
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - KAFKA_ADDRESS=138.2.67.89:9092
      - CARD_NO_STORE_NAME=card-no-store
      - BALANCE_TOPIC_NAME=balances
      - LIMIT_TOPIC_NAME=limits

  purchase-processor:
    container_name: purchase-processor
    build:
      context: ./purchase-processor
      dockerfile: Dockerfile
    environment:
      - KAFKA_ADDRESS=138.2.67.89:9092
      - ACCEPTED_PURCHASE_TOPIC_NAME=accepted-purchases
      - BALANCE_TOPIC_NAME=balances
      - LIMIT_TOPIC_NAME=limits
      - REJECTED_PURCHASE_TOPIC_NAME=rejected-purchases
      - PURCHASE_TOPIC_NAME=purchases

  purchase-producer:
    container_name: purchase-producer
    build:
      context: ./purchase-producer
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - KAFKA_ADDRESS=138.2.67.89:9092
      - PURCHASE_TOPIC_NAME=purchases

